var path=require('path');
var ExtractTextPlugin=require('extract-text-webpack-plugin');
var config={
	entry:{
		main:"./main"
	},
	output:{
		path:path.join(__dirname,'./dist'),
		publicPath:'/dist/',
		filename:'[name].js',
		chunkFilename:'[name].chunk.js'
	},
	module:{
		rules:[
		{
			test:/\.css$/,
			use:ExtractTextPlugin.extract({
				use:'css-loader',
				fallback:'style-loader'
			})
		},
		{
			test:/\.vue$/,
			loader:'vue-loader',
			options:{
				loaders:{
					css:ExtractTextPlugin.extract({
						use:[{
							loader:'css-loader'
						},{
							loader:'less-loader'
						}],
						fallback:'vue-style-loader'
					})
				}
			}
		},
		{
			test: /\.less$/,
			use:ExtractTextPlugin.extract({
				use:[{
					loader:'css-loader'
				},{
					loader:'less-loader'
				}],
				fallback:'style-loader'
			})
		},
		{
			test:/\.js$/,
			loader:'babel-loader',
			options:{
				presets:['es2015']
			},
			exclude:/node_modules/
		},
		{
			test:/\.(gift|jpg|jpeg|png|woff|svg|eot|ttf)\??.*$/,
			loader:'url-loader?limit=1024'
		}
		]
	},
	plugins:[
	new ExtractTextPlugin({filename:'[name].css',allChunks:true})
	]
};
module.exports=config;